# Source: service.yaml
apiVersion: v1
kind: Service
metadata:
  name: be-auth-service
  namespace: cessazione
  labels:
    app.kubernetes.io/name: be-auth-service
    app.kubernetes.io/instance: be-auth-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: be-auth-service
    app.kubernetes.io/instance: be-auth-service
---
# Source: gedocc-api/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-auth-service
  namespace: cessazione
  labels:
    app.kubernetes.io/name: be-auth-service
    app.kubernetes.io/instance: be-auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: be-auth-service
      app.kubernetes.io/instance: be-auth-service
  template:
    metadata:
      namespace: cessazione
      labels:
        app.kubernetes.io/name: be-auth-service
        app.kubernetes.io/instance: be-auth-service
    spec:
      imagePullSecrets:
        - name: jfrogregistry
      serviceAccountName: default
      securityContext:
        {}
      containers:
        - name: be-auth-service
          securityContext:
            {}
          image: almaviva.jfrog.io/difesa-sipad-docker/cessazione/be-auth-service:#{Build.BuildId}#
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {}
---
